### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by angelacuahutle**
Dear TSE, 

This is the first Milestone of this project where I have covered the following task:

|x| Setup project with Webpack
|x| Implemented HTML 
|x| Run linters
|x| Update README template 

Thanks

### CODE REVIEW

**Comment by leolpaz** [comment]
Hi @angelacuahutle , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that while it's the setup it appeared on my dashboard as the "Hit the API milestone", it's possible that you accidentally submitted the project for review under that, instead of the "Setup" on day 2, kindly submit it again, under the correct milestone in the dashboard.

If that was NOT the case, kindly submit it again, if the same thing happens, kindly contact student success

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Dipeshtwis — CHANGES_REQUESTED** [review]
Hi @angelacuahutle, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

- [x] In the README there is a link broken of the `live demo` and the `screenshot`. Please update it. Also, I got an error while running the `npm start`. Please fix it. Right now I have checked your project by opening the `dist/index.html` file.

Screenshot from 2021-12-18 03-26-57


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by angelacuahutle** [comment]
I have implemented the required changes. 

A folder was set in a different path so I installed correctly!

Thanks

**Comment by angelacuahutle** [comment]
I also update the README!

**Review by sinansevgi — APPROVED** [review]
# Approved :heavy_check_mark: 

Hi @angelacuahutle, 

Great Work!
Your project is complete!  
Congratulations! 🎉

You can merge this pull request and continue with your journey :wave: 


Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
